#
# Project EmeRails - Codename Ocarina
#
# Copyright (c) 2008, 2017 Claudio Procida
# http://www.emeraldion.it
#
#
version: '2'

services:

  db:
    image: mysql:5.5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: emerails
      MYSQL_USER: emerails
      MYSQL_PASSWORD: emerails

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - db
    links:
      - db:mysql
    volumes:
      - .:/var/www/html
    environment:
      EMERAILS_DB_PASSWORD: emerails
      EMERAILS_DB_USER: emerails
      EMERAILS_DB_NAME: emerails

volumes:
  db_data: