<?php
	/**
	 *	Project EmeRails - Codename Ocarina
	 *
	 *	© 2008 Claudio Procida
	 *	http://www.emeraldion.it
	 *
	 */
	 
	require_once(dirname(__FILE__) . "/../config/db.conf.php");
	
	/**
	 *	@class DBConn
	 *	@short Database connection manager.
	 */
	class DBConn
	{
		static $queries_count = 0;
		
		var $link;
		var $query;
		var $result;
		
		/**
		 *	@fn connect
		 *	@short Connects to the database.
		 */
		function connect()
		{
			if (!is_resource($this->link) || get_resource_type($this->link) != "mysql link")
			{
				$this->link = mysql_connect(DB_HOST, DB_USER, DB_PASS);
				mysql_select_db(DB_NAME) or die("Cannot connect: " . mysql_error());
			}
		}
		
		/**
		 *	@fn select_db
		 *	@short Selects the desired database.
		 *	@param database_name The name of the database.
		 */
		function select_db($database_name)
		{
			$this->connect();
			return mysql_select_db($database_name, $this->link);
		}
		
		/**
		 *	@fn close
		 *	@short Closes the connection to the database.
		 */
		function close()
		{
			if (is_resource($this->link) && get_resource_type($this->link) == "mysql link")
			{
				mysql_close($this->link);
			}
		}
		
		/**
		 *	@fn prepare
		 *	@short Prepares a query for execution
		 *	@param query The query to execute.
		 */
		function prepare($query)
		{
			$this->connect();
			
			$args = func_get_args();
			$args_len = func_num_args();
			if ($args_len > 1)
			{
				for ($i = 1; $i < $args_len; $i++)
				{
					$query = preg_replace("/\{$i\}/", mysql_real_escape_string($args[$i], $this->link), $query, 1);
				}
			}
			$this->query = $query;
			
			if (DB_DEBUG)
			{
				$this->print_query();
			}
		}
		
		/**
		 *	@fn exec
		 *	@short Executes a query.
		 */
		function exec()
		{
			$this->connect();
			$this->result = mysql_query($this->query, $this->link) or die("Error ({$this->query}): " . mysql_error());
			
			self::$queries_count++;
			
			return  $this->result;
		}
		
		/**
		 *	@fn insert_id
		 *	@short Returns the id generated by the last INSERT query.
		 */
		function insert_id()
		{
			return mysql_insert_id($this->link());
		}
		
		/**
		 *	@fn escape
		 *	@short Escapes the given value to avoid SQL injections.
		 *	@param value The value to escape.
		 */
		function escape($value)
		{
			$this->connect();
			return mysql_real_escape_string($value, $this->link);
		}
		
		function result($pos = 0, $name = NULL)
		{
			return mysql_result($this->result, $pos, $name);
		}
		
		/**
		 *	@short Returns the number of rows returned by a previous SELECT query.
		 */
		function num_rows()
		{
			return mysql_num_rows($this->result);
		}
		
		/**
		 *	@short Returns the number of rows affected by a previous INSERT, UPDATE or DELETE query.
		 */
		function affected_rows()
		{
			return mysql_affected_rows($this->result);
		}
		
		function fetch_assoc()
		{
			return mysql_fetch_assoc($this->result);
		}
		
		function free_result()
		{
			mysql_free_result($this->result);
		}
		
		function print_query()
		{
			echo <<<EOT
			<pre class="db-debug">{$this->query}</pre>
EOT;
		}
	}
	
	$db = new DBConn();
	$db->connect();
	
?>