EmeRails: Localization Class Reference
Localization Class Reference
Adds localization support to EmeRails.
Static Public Member Functions
static localize ($term)
Localizes a string according to the current language settings.
static add_strings_table ($controller)
Adds another strings table for a desired controller.
Static Public Attributes
static $languages = array('it', 'en', 'es')
Array of supported languages.
Static Private Member Functions
static wrap ($term)
Wraps a string in a parent HTML element to add debug style selectors.
static load_strings_file ($lang= 'en', $controller=NULL)
Loads the string file for the desired controller and language.
static load_strings_table ()
Loads the string table for the current controller and language.
Static Private Attributes
static $strings_table
Table of translated strings.
Detailed Description
Adds localization support to EmeRails.
Definition at line 18 of file localization.php.
Member Function Documentation
Localization::add_strings_table ($controller) static
Adds another strings table for a desired controller.
Language is obtained by the request parameters.
Parameters
controller The name of the controller.
Definition at line 53 of file localization.php.
Referenced by BaseController\render_component().
Localization::load_strings_file ($lang = 'en', $controller = NULL) static private
Loads the string file for the desired controller and language.
Parameters
lang The language for the strings file.
controller The name of the controller.
Definition at line 80 of file localization.php.
Localization::load_strings_table () static private
Loads the string table for the current controller and language.
Controller and language are obtained by the request parameters.
Definition at line 104 of file localization.php.
Localization::localize ($term) static
Localizes a string according to the current language settings.
Parameters
term The string to be translated.
Definition at line 37 of file localization.php.
Referenced by localized().
Localization::wrap ($term) static private
Wraps a string in a parent HTML element to add debug style selectors.
Parameters
term The string to be wrapped.
Definition at line 68 of file localization.php.
References LOCALIZATION_DEBUG, and span().
Member Data Documentation
Localization::$languages = array('it', 'en', 'es') static
Array of supported languages.
languages
Definition at line 24 of file localization.php.
Referenced by BaseController\expire_cached_page().
Localization::$strings_table static private
Table of translated strings.
strings_table
Definition at line 30 of file localization.php.
The documentation for this class was generated from the following file:
/Users/delphine/Development/Git/emeraldion/emerails/helpers/localization.php