EmeRails: ErrorController Class Reference
ErrorController Class Reference
Controller class for HTTP errors.
Public Member Functions
_404 ()
Handles 404 Not Found HTTP errors.
_403 ()
Handles 403 Forbidden HTTP errors.
_405 ()
Handles 405 Method Not Supported HTTP errors.
_500 ()
Handles 500 Internal Server Error HTTP errors.
Public Member Functions inherited from BaseController
BaseController ()
Default constructor for controller objects.
link_to ($text, $params=array())
Links to another action.
link_to_remote ($text, $params=array())
Links to another action, with AJAX support.
button_to ($text, $params=array())
Creates a button that links to another action.
url_to ($params)
Creates a URL to an action.
url_to_myself ($relative=TRUE)
Creates a URL to the current action.
make_relative_url ($params)
Creates a URL to an action.
render ($params)
Requests the rendering of the response.
render_as_string ($params)
Requests the rendering of the response as a string.
render_page ()
Renders the page as a response for the current request.
render_component ($params)
Renders a view from a controller other than self.
set_title ($title)
Sets the title for the current page.
flash ($message, $type= 'error')
Shows a message to the user, with an optional type qualifier.
index ()
This is the default action method.
Private Member Functions
error ()
Private common error handler.
Additional Inherited Members
Public Attributes inherited from BaseController
$name
The name of the controller.
$action
The name of the action.
$title
A title for the page.
Protected Member Functions inherited from BaseController
initialize ()
Initializes the controller object.
init ()
Custom initialization for the controller object.
before_filter ($filter, $params=NULL)
Registers a function as a filter to be executed before the action is invoked.
after_filter ($filter, $params=NULL)
Registers a function as a filter to be executed after the action is invoked.
caches_page ($page)
Requests that a page be cached.
conditionally_caches_page ($page, $condition=TRUE)
Requests that a page be cached when a condition is verified.
caches_action ($page)
Requests that an action be cached.
cached_page_exists ()
Checks if a cached version of the current action exists.
cached_page_filename ()
Returns a name for the cached page of current action.
expire_cached_page ($params)
Requests that the page(s) defined by params be removed from the caches.
redirect_to ($params)
Redirects the response to another action, or URL.
refresh ($amount)
Refreshes current page after a given amount of time.
redirect_to_referrer ($or_else=NULL)
Redirects the response to the URL which is contained in the HTTP_REFERER server variable (i.e., performs a back redirection). If no HTTP_REFERER is set, and if passed the optional parameter or_else, the latter is used for an explicit redirection.
unknown_action ()
render_layout ($params)
Renders the layout for the current view.
load_part_contents ($filename)
Loads the contents of the desired view file.
strip_external_php_tags ($php_code)
Strips beginning and ending delimiters from the given PHP code.
compress ()
Compresses the response with gzip encoding.
Protected Attributes inherited from BaseController
$type = 'html'
An extension for action pages.
$mimetype = 'text/html'
A MIME type for the response.
Detailed Description
Controller class for HTTP errors.
Project EmeRails - Codename Ocarina
Copyright (c) 2008, 2015 Claudio Procida http://www.emeraldion.it
ErrorController is responsible for handling HTTP errors. Feel free to improve this class by adding your custom error handling code.
Definition at line 18 of file error_controller.php.
Member Function Documentation
ErrorController::_403 ()
Handles 403 Forbidden HTTP errors.
Definition at line 33 of file error_controller.php.
References error().
ErrorController::_404 ()
Handles 404 Not Found HTTP errors.
Definition at line 24 of file error_controller.php.
References error().
ErrorController::_405 ()
Handles 405 Method Not Supported HTTP errors.
Definition at line 42 of file error_controller.php.
References error().
ErrorController::_500 ()
Handles 500 Internal Server Error HTTP errors.
Definition at line 51 of file error_controller.php.
References error().
ErrorController::error () private
Private common error handler.
Definition at line 60 of file error_controller.php.
References BaseController\render().
Referenced by _403(), _404(), _405(), and _500().
The documentation for this class was generated from the following file:
/Users/delphine/Development/Git/emeraldion/emerails/controllers/error_controller.php