EmeRails: CommonTest Class Reference
CommonTest Class Reference
Public Member Functions
test_pluralize ()
test_singularize ()
test_ends_with ()
test_class_name_to_table_name ()
test_table_name_to_class_name ()
test_joined_lower ()
test_joined_lower_to_camel_case ()
test_camel_case_to_joined_lower ()
test_class_name_to_foreign_key ()
test_table_name_to_foreign_key ()
Detailed Description
Definition at line 5 of file common.test.php.
Member Function Documentation
CommonTest::test_camel_case_to_joined_lower ()
Definition at line 81 of file common.test.php.
References camel_case_to_joined_lower().
CommonTest::test_class_name_to_foreign_key ()
Definition at line 89 of file common.test.php.
References class_name_to_foreign_key().
CommonTest::test_class_name_to_table_name ()
Definition at line 50 of file common.test.php.
References class_name_to_table_name().
CommonTest::test_ends_with ()
Definition at line 43 of file common.test.php.
References ends_with().
CommonTest::test_joined_lower ()
Definition at line 66 of file common.test.php.
References joined_lower().
CommonTest::test_joined_lower_to_camel_case ()
Definition at line 73 of file common.test.php.
References joined_lower_to_camel_case().
CommonTest::test_pluralize ()
Definition at line 7 of file common.test.php.
References pluralize().
CommonTest::test_singularize ()
Definition at line 25 of file common.test.php.
References singularize().
CommonTest::test_table_name_to_class_name ()
Definition at line 58 of file common.test.php.
References table_name_to_class_name().
CommonTest::test_table_name_to_foreign_key ()
Definition at line 97 of file common.test.php.
References table_name_to_foreign_key().
The documentation for this class was generated from the following file:
test/unit/include/common.test.php