EmeRails: MysqliAdapter Class Reference
MysqliAdapter Class Reference
MySQLi Database adapter.
Public Member Functions
connect ()
Connects to the database.
select_db ($database_name)
Selects the desired database.
close ()
Closes the connection to the database.
prepare ($query)
Prepares a query for execution.
exec ()
Executes a query.
insert_id ()
Returns the id generated by the last INSERT query.
escape ($value)
Escapes the given value to avoid SQL injections.
result ($pos=0, $colname=NULL)
Returns a single result of the last SELECT query.
num_rows ()
Returns the number of rows returned by a previous SELECT query.
affected_rows ()
Returns the number of rows affected by a previous INSERT, UPDATE or DELETE query.
fetch_assoc ()
Returns the current row of the resultset as an associative array.
fetch_array ()
Returns the current row of the resultset as an array.
free_result ()
Releases the result of the last query.
print_query ()
Prints the last query for debug.
Public Attributes
const NAME = "mysqli"
Name of this adapter.
$link
Connection link to the database.
$query
Query for the database.
$result
The result of the last query.
Static Public Attributes
static $queries_count = 0
Counter for queries executed.
Detailed Description
MySQLi Database adapter.
Definition at line 10 of file mysqli_adapter.php.
Member Function Documentation
MysqliAdapter::affected_rows ()
Returns the number of rows affected by a previous INSERT, UPDATE or DELETE query.
Implements DbAdapter.
Definition at line 174 of file mysqli_adapter.php.
MysqliAdapter::close ()
Closes the connection to the database.
Implements DbAdapter.
Definition at line 72 of file mysqli_adapter.php.
MysqliAdapter::connect ()
Connects to the database.
Implements DbAdapter.
Definition at line 46 of file mysqli_adapter.php.
Referenced by escape(), exec(), prepare(), and select_db().
MysqliAdapter::escape ($value)
Escapes the given value to avoid SQL injections.
Parameters
value The value to escape.
Implements DbAdapter.
Definition at line 129 of file mysqli_adapter.php.
References connect().
MysqliAdapter::exec ()
Executes a query.
Implements DbAdapter.
Definition at line 105 of file mysqli_adapter.php.
References $result, connect(), and result().
MysqliAdapter::fetch_array ()
Returns the current row of the resultset as an array.
Implements DbAdapter.
Definition at line 192 of file mysqli_adapter.php.
References result().
MysqliAdapter::fetch_assoc ()
Returns the current row of the resultset as an associative array.
Implements DbAdapter.
Definition at line 183 of file mysqli_adapter.php.
References result().
MysqliAdapter::free_result ()
Releases the result of the last query.
Implements DbAdapter.
Definition at line 201 of file mysqli_adapter.php.
References result().
MysqliAdapter::insert_id ()
Returns the id generated by the last INSERT query.
Implements DbAdapter.
Definition at line 119 of file mysqli_adapter.php.
MysqliAdapter::num_rows ()
Returns the number of rows returned by a previous SELECT query.
Implements DbAdapter.
Definition at line 165 of file mysqli_adapter.php.
References result().
MysqliAdapter::prepare ($query)
Prepares a query for execution.
Parameters
query The query to execute.
Implements DbAdapter.
Definition at line 82 of file mysqli_adapter.php.
References $query, connect(), and print_query().
MysqliAdapter::print_query ()
Prints the last query for debug.
Implements DbAdapter.
Definition at line 210 of file mysqli_adapter.php.
Referenced by prepare().
MysqliAdapter::result ($pos = 0, $colname = NULL)
Returns a single result of the last SELECT query.
Parameters
row The row of the resultset.
colname The name (or the alias, if applicable) of the desired row.
Implements DbAdapter.
Definition at line 142 of file mysqli_adapter.php.
Referenced by exec(), fetch_array(), fetch_assoc(), free_result(), and num_rows().
MysqliAdapter::select_db ($database_name)
Selects the desired database.
Parameters
database_name The name of the database.
Implements DbAdapter.
Definition at line 62 of file mysqli_adapter.php.
References connect().
Member Data Documentation
MysqliAdapter::$link
Connection link to the database.
link
Definition at line 28 of file mysqli_adapter.php.
MysqliAdapter::$queries_count = 0 static
Counter for queries executed.
queries_count
Definition at line 22 of file mysqli_adapter.php.
MysqliAdapter::$query
Query for the database.
query
Definition at line 34 of file mysqli_adapter.php.
Referenced by prepare().
MysqliAdapter::$result
The result of the last query.
result
Definition at line 40 of file mysqli_adapter.php.
Referenced by exec().
const MysqliAdapter::NAME = "mysqli"
Name of this adapter.
NAME
Definition at line 16 of file mysqli_adapter.php.
The documentation for this class was generated from the following file:
include/mysqli_adapter.php