EmeRails: QueryString Class Reference
QueryString Class Reference
Helper class to manipulate query strings.
Static Public Member Functions
static from_assoc ($parts)
Writes the query string for an associative array.
static to_assoc ($string)
Parses a query string into an associative array.
static replace ($key, $val)
Public Attributes
const SEPARATOR = '&'
Query string separator, defaults to '&'.
const EQUALS = '='
Key-value separator, defaults to '='.
Detailed Description
Helper class to manipulate query strings.
Definition at line 24 of file query_string.php.
Member Function Documentation
QueryString::from_assoc ($parts) static
Writes the query string for an associative array.
Parameters
parts The associative array
Definition at line 43 of file query_string.php.
References SEPARATOR.
Referenced by QueryStringUnitTest\test_from_assoc().
static QueryString::replace ($key, $val) static
Definition at line 66 of file query_string.php.
Referenced by QueryStringUnitTest\test_replace().
QueryString::to_assoc ($string) static
Parses a query string into an associative array.
Parameters
string The query string
Definition at line 54 of file query_string.php.
References QueryString_explode_item(), and SEPARATOR.
Referenced by QueryStringUnitTest\test_to_assoc().
Member Data Documentation
const QueryString::EQUALS = '='
Key-value separator, defaults to '='.
Definition at line 36 of file query_string.php.
Referenced by QueryString_explode_item(), and QueryString_implode_item().
const QueryString::SEPARATOR = '&'
Query string separator, defaults to '&'.
Definition at line 30 of file query_string.php.
Referenced by from_assoc(), and to_assoc().
The documentation for this class was generated from the following file:
helpers/query_string.php