EmeRails: QueryStringUnitTest Class Reference
QueryStringUnitTest Class Reference
Test case for QueryString helper object.
Public Member Functions
test_from_assoc ()
Test method for from_assoc().
test_to_assoc ()
Test method for to_assoc().
test_replace ()
Test method for replace().
Additional Inherited Members
Static Public Member Functions inherited from UnitTest
static assertInRange ($expr, $min, $max, $message= '')
Asserts that an expression is in the range of two values.
Detailed Description
Test case for QueryString helper object.
Definition at line 9 of file query_string.test.php.
Member Function Documentation
QueryStringUnitTest::test_from_assoc ()
Test method for from_assoc().
Definition at line 15 of file query_string.test.php.
References QueryString\from_assoc().
QueryStringUnitTest::test_replace ()
Test method for replace().
Definition at line 35 of file query_string.test.php.
References QueryString\replace().
QueryStringUnitTest::test_to_assoc ()
Test method for to_assoc().
Definition at line 25 of file query_string.test.php.
References QueryString\to_assoc().
The documentation for this class was generated from the following file:
test/unit/helpers/query_string.test.php