EmeRails: ActiveRecord Class Reference
ActiveRecord Class Reference
The abstract base class for DB-backed model objects.
Public Member Functions
__construct ($_values=NULL)
Constructs and initializes an ActiveRecord object.
belongs_to ($table_name)
Loads the parent of the receiver in a one-to-many relationship.
has_many ($table_name, $params=array())
Loads the children of the receiver in a one-to-many relationship.
has_and_belongs_to_many ($table_name, $params=array())
Loads the object network the receiver belongs to in a many-to-many relationship.
has_one ($table_name)
Loads the child the receiver in a one-to-one relationship.
find_by_query ($query)
Returns an array of model objects by executing a custom SELECT query.
find_all ($params=array())
Returns an array of model objects that satisfy the requirements expressed in the params argument.
find_by_id ($id)
Populates an object with the values of the DB row whose primary key value is id.
count_all ($params=array())
Returns the count of model objects that satisfy the requirements expressed in the params argument.
save ()
Requests the receiver to save its data in the bound table.
delete ($optimize=TRUE)
Deletes an object's database counterpart.
permalink ($relative=TRUE)
Provides a unique permalink URL for the receiver object.
__set ($key, $value)
Magic method to set the value of a property.
__get ($key)
Magic method to get the value of a property.
__isset ($key)
Magic method to determine if a property exists.
__unset ($key)
Magic method to unset a property.
Static Public Member Functions
static find ($id, $classname= 'ActiveRecord')
Returns an object whose primary key value is id.
Static Public Attributes
static $columns = array()
Array of columns for the model object.
static $class_initialized = array()
Array containing initialization information for subclasses.
static $belongs_to_classes = array()
Array containing information on parent tables for subclasses.
static $has_many_classes = array()
Array containing information on child tables for subclasses.
static $object_pool = array()
Pool of objects already fetched from database.
Protected Member Functions
init ($values)
Performs specialized initialization tasks.
relative_url ()
Provides a relative URL that will be used by the permalink public method.
Protected Attributes
$table_name
Name of the table bound to this model class.
$primary_key = 'id'
Name of the primary key column for the bound table.
$foreign_key_name
Used to create the name of foreign key column in tables that are in a relationship with the bound table.
Private Member Functions
get_table_name ()
Returns the name of the table bound to this class.
get_foreign_key_name ()
Returns the name of the foreign key for this class.
get_primary_key ()
Returns the name of the primary key for this class.
has_column ($key)
Verifies the existence of a column named key in the bound table.
Static Private Member Functions
static _set_initialized ($classname, $initialized)
Marks the class classname as initialized.
static _is_initialized ($classname)
Tells whether the class classname has already been initialized.
static _set_columns ($classname, $cols)
Stores the columns for the desired class.
static _get_columns ($classname)
Returns the columns for the desired class.
static _add_to_pool ($classname, $id, $obj)
Adds an object to the object pool.
static _get_from_pool ($classname, $id)
Retrieves an object from the object pool.
Private Attributes
$values
Array of values for the columns of model object.
Detailed Description
The abstract base class for DB-backed model objects.
Project EmeRails - Codename Ocarina
Copyright (c) 2008, 2017 Claudio Procida http://www.emeraldion.it
Every object of a subclass of ActiveRecord are mapped 1:1 to records of a table in a relational Database. Naming conventions assume that if the ActiveRecord subclass is called MyProduct, database records are stored in a table called my_products. Conversely, if an object of another class is in a relation with your object, it is assumed that a foreign key called my_product_id exists in the other table. Of course this is overridable by setting explicitly $table_name and $foreign_key to a value of your choice.
Definition at line 23 of file base.php.
Constructor & Destructor Documentation
ActiveRecord::__construct ($_values = NULL)
Constructs and initializes an ActiveRecord object.
Due to the lack of a static class initialization method, the default constructor is in charge of gathering information about the bound table columns the first time an object is created. Subsequent creations will use the values stored in static class variables. Subclassers don't need to override the constructor. They can in turn override the init method in order to perform custom initialization.
Parameters
values Column values to initialize the object.
Definition at line 93 of file base.php.
References $columns, Db\close_connection(), Db\get_connection(), get_table_name(), and init().
Member Function Documentation
ActiveRecord::__get ($key)
Magic method to get the value of a property.
Parameters
key The key of the desired property.
Definition at line 683 of file base.php.
ActiveRecord::__isset ($key)
Magic method to determine if a property exists.
Parameters
key The key to test.
Definition at line 702 of file base.php.
ActiveRecord::__set ($key, $value)
Magic method to set the value of a property.
Parameters
key The key of the property.
value The value of the property.
Definition at line 666 of file base.php.
References has_column().
ActiveRecord::__unset ($key)
Magic method to unset a property.
Parameters
key The key to unset.
Definition at line 724 of file base.php.
ActiveRecord::_add_to_pool ($classname, $id, $obj) static private
Adds an object to the object pool.
Parameters
classname Name of the class for the desired object.
id Primary key value for the desired object.
obj The object to add to the pool.
Definition at line 801 of file base.php.
ActiveRecord::_get_columns ($classname) static private
Returns the columns for the desired class.
Parameters
classname Name of the class for the desired object.
Definition at line 785 of file base.php.
ActiveRecord::_get_from_pool ($classname, $id) static private
Retrieves an object from the object pool.
Parameters
classname Name of the class for the desired object.
id Primary key value for the desired object.
Definition at line 816 of file base.php.
ActiveRecord::_is_initialized ($classname) static private
Tells whether the class classname has already been initialized.
Parameters
classname The name of the class that you want to inspect.
Returns
TRUE if the class has been initialized, FALSE otherwise.
Definition at line 760 of file base.php.
ActiveRecord::_set_columns ($classname, $cols) static private
Stores the columns for the desired class.
Parameters
classname Name of the class for the desired object.
cols The columns of the model object.
Definition at line 775 of file base.php.
ActiveRecord::_set_initialized ($classname, $initialized) static private
Marks the class classname as initialized.
This method allows ActiveRecord to keep track of what subclasses have already been initialized by inspectioning the bound database table schema, whithout the need for a per-class initialization method.
Parameters
classname The name of the class that should be marked as initialized
initialized TRUE if the class should be considered initialized, FALSE otherwise.
Definition at line 749 of file base.php.
ActiveRecord::belongs_to ($table_name)
Loads the parent of the receiver in a one-to-many relationship.
Parameters
table_name The name of the parent table.
Definition at line 210 of file base.php.
References $columns, $table_name, singularize(), table_name_to_class_name(), and table_name_to_foreign_key().
ActiveRecord::count_all ($params = array())
Returns the count of model objects that satisfy the requirements expressed in the params argument.
This method lets you count all objects of this class that satisfy a custom set of requirements, which you can express by setting the following keys of the params argument:
where_clause You can express a custom SQL WHERE expression here (e.g. date < '2008-05-01')
Parameters
params An array of parameters for the underlying SQL query.
Definition at line 481 of file base.php.
References Db\close_connection(), Db\get_connection(), and get_table_name().
ActiveRecord::delete ($optimize = TRUE)
Deletes an object's database counterpart.
This method performs a DELETE SQL statement on the table bound to the receiver's class, requesting the deletion of the object whose primary key is equal to the receiver's primary key value. If the object has been created programmatically and lacks a primary key value, this method has no effect.
Parameters
bool cleanup Set to FALSE if you do not want the table to be optimized after deletion.
Definition at line 598 of file base.php.
References Db\close_connection(), Db\get_connection(), and get_table_name().
ActiveRecord::find ($id, $classname = 'ActiveRecord') static
Returns an object whose primary key value is id.
Due to limitations of PHP, a static method always apply to the superclass. We have to explicitly reference the name of the subclass in order to create the right object.
Parameters
id The value of the primary key.
classname The name of the subclass to apply this static method to.
Definition at line 429 of file base.php.
ActiveRecord::find_all ($params = array())
Returns an array of model objects that satisfy the requirements expressed in the params argument.
This method lets you find all objects of this class that satisfy a custom set of requirements, which you can express by setting the following keys of the params argument:
where_clause You can express a custom SQL WHERE expression here (e.g. date < '2008-05-01')
order_by You can express a custom SQL ORDER BY expression here (e.g. date DESC)
limit You can express a custom limit for the returned results.
start You can express a custom start for the returned results.
Parameters
params An array of parameters for the underlying SQL query.
Definition at line 375 of file base.php.
References Db\close_connection(), Db\get_connection(), and get_table_name().
ActiveRecord::find_by_id ($id)
Populates an object with the values of the DB row whose primary key value is id.
This instance method populates the receiver object with the contents of the DB row whose primary key is id.
Parameters
id The primary key of the desired DB row.
Returns
This method returns TRUE if such row exists, FALSE otherwise.
Definition at line 444 of file base.php.
References $columns, $values, Db\close_connection(), Db\get_connection(), and get_table_name().
ActiveRecord::find_by_query ($query)
Returns an array of model objects by executing a custom SELECT query.
Finder methods
This is a powerful instance method to retrieve objects from the database with a custom query. You can, among other things, do LEFT JOIN queries here.
Parameters
query The SELECT query to fetch objects.
Definition at line 337 of file base.php.
References Db\close_connection(), and Db\get_connection().
ActiveRecord::get_foreign_key_name () private
Returns the name of the foreign key for this class.
This method returns the name of the column to lookup when considering relations with objects of this class. If the ActiveRecord subclass is called MyRecord, the foreign key name will be my_record_id. Of course you can override this behavior by setting explicitly the value of $foreign_key_name in the declaration of your class.
Definition at line 167 of file base.php.
References $foreign_key_name, and class_name_to_foreign_key().
Referenced by has_and_belongs_to_many(), has_many(), and has_one().
ActiveRecord::get_primary_key () private
Returns the name of the primary key for this class.
This method returns the name of the primary key in the table bound to this class. By default, ActiveRecord considers as primary key a column named id. Of course you can override this behavior by setting explicitly the value of $primary_key in the declaration of your class.
Definition at line 184 of file base.php.
References $primary_key.
ActiveRecord::get_table_name () private
Returns the name of the table bound to this class.
This method returns the name of the table which contains data for objects of this class. If the ActiveRecord subclass is called MyRecord, the table name will be my_records. Of course you can override this behavior by setting explicitly the value of $table_name in the declaration of your class.
Definition at line 149 of file base.php.
References $table_name, and class_name_to_table_name().
Referenced by __construct(), count_all(), delete(), find_all(), find_by_id(), and save().
ActiveRecord::has_and_belongs_to_many ($table_name, $params = array())
Loads the object network the receiver belongs to in a many-to-many relationship.
Parameters
table_name The name of the peer table.
params An array of conditions. For the semantics, see find_all
See also
find_all
Definition at line 266 of file base.php.
References $table_name, Db\close_connection(), Db\get_connection(), get_foreign_key_name(), and table_name_to_class_name().
ActiveRecord::has_column ($key) private
Verifies the existence of a column named key in the bound table.
Parameters
key The name of the column to check.
Definition at line 198 of file base.php.
References $columns.
Referenced by __set().
ActiveRecord::has_many ($table_name, $params = array())
Loads the children of the receiver in a one-to-many relationship.
Parameters
table_name The name of the child table.
params An array of conditions. For the semantics, see find_all
See also
find_all
Definition at line 235 of file base.php.
References $table_name, get_foreign_key_name(), singularize(), and table_name_to_class_name().
ActiveRecord::has_one ($table_name)
Loads the child the receiver in a one-to-one relationship.
Parameters
table_name The name of the child table.
params An array of conditions. For the semantics, see find_all
See also
find_all
Definition at line 312 of file base.php.
References $table_name, get_foreign_key_name(), singularize(), and table_name_to_class_name().
ActiveRecord::init ($values) protected
Performs specialized initialization tasks.
Subclassers will use this method to perform custom initialization.
Note
The default implementation simply does nothing.
Parameters
values An array of column-value pairs to initialize the receiver.
Definition at line 137 of file base.php.
Referenced by __construct().
ActiveRecord::permalink ($relative = TRUE)
Provides a unique permalink URL for the receiver object.
Subclassers that wish to provide custom permalinks for objects should not override this method. Override the relative_url method instead.
Parameters
relative TRUE if the permalink should not contain the protocol and domain part of the URL, FALSE if you want them.
Definition at line 640 of file base.php.
References APPLICATION_ROOT, and relative_url().
ActiveRecord::relative_url () protected
Provides a relative URL that will be used by the permalink public method.
Subclassers that wish to provide custom permalinks for objects should override this method. You should return the URL portion after the APPLICATION_ROOT part only.
Definition at line 627 of file base.php.
Referenced by permalink().
ActiveRecord::save ()
Requests the receiver to save its data in the bound table.
This method has two distinct effects. If called on an object fetched from the table, it performs an UPDATE SQL statement to update the table data to the new values. If called on an object created programmatically, it performs an INSERT SQL statement, and sets the object's primary key value to the value resulting by the insert.
Returns
This method returns TRUE if the object has been saved successfully.
Definition at line 514 of file base.php.
References $columns, $primary_key, Db\close_connection(), Db\get_connection(), and get_table_name().
Member Data Documentation
ActiveRecord::$belongs_to_classes = array() static
Array containing information on parent tables for subclasses.
belongs_to_classes
Definition at line 41 of file base.php.
ActiveRecord::$class_initialized = array() static
Array containing initialization information for subclasses.
class_initialized
Definition at line 35 of file base.php.
ActiveRecord::$columns = array() static
Array of columns for the model object.
columns
Definition at line 29 of file base.php.
Referenced by __construct(), belongs_to(), find_by_id(), has_column(), and save().
ActiveRecord::$foreign_key_name protected
Used to create the name of foreign key column in tables that are in a relationship with the bound table.
foreign_key_name
Set this attribute only when the foreign key that references objects of this class is not the canonical name (e.g. 'product' for class Product).
Definition at line 74 of file base.php.
Referenced by get_foreign_key_name().
ActiveRecord::$has_many_classes = array() static
Array containing information on child tables for subclasses.
has_many_classes
Definition at line 47 of file base.php.
ActiveRecord::$object_pool = array() static
Pool of objects already fetched from database.
object_pool
Definition at line 53 of file base.php.
ActiveRecord::$primary_key = 'id' protected
Name of the primary key column for the bound table.
primary_key
Set this attribute only when the primary key of the bound table is not the canonical id.
Definition at line 66 of file base.php.
Referenced by get_primary_key(), and save().
ActiveRecord::$table_name protected
Name of the table bound to this model class.
table_name
Definition at line 59 of file base.php.
Referenced by belongs_to(), get_table_name(), has_and_belongs_to_many(), has_many(), and has_one().
ActiveRecord::$values private
Array of values for the columns of model object.
values
Definition at line 80 of file base.php.
Referenced by find_by_id().
The documentation for this class was generated from the following file:
models/base.php