EmeRails: Db Class Reference
Db Class Reference
Implements an abstraction of a Database connection manager.
Static Public Member Functions
static get_adapter ($name=DB_ADAPTER)
Returns a database adapter registered under name.
static register_adapter ($adapter, $name)
Registers a database adapter under name.
static get_default_adapter ()
Returns the default database adapter.
static get_connection ($name=DB_ADAPTER)
Returns a connection for the requested adapter.
static close_connection ($conn, $name=DB_ADAPTER)
Closes a connection for the requested adapter.
static show_pool ()
Static Private Attributes
static $adapters = array()
List of registered adapters.
static $pool = array()
Connections pool.
static $conn_counter = 0
Connections counter.
Detailed Description
Implements an abstraction of a Database connection manager.
Definition at line 20 of file db.inc.php.
Member Function Documentation
Db::close_connection ($conn, $name = DB_ADAPTER) static
Closes a connection for the requested adapter.
The connection is actually never closed, it is just marked as free and kept in the pool for later reuse.
Parameters
conn The connection that should be closed
name The name of the adapter
Definition at line 114 of file db.inc.php.
References DB_CONNECTION_KEY, and DB_IN_USE_KEY.
Referenced by ActiveRecord\__construct(), ActiveRecord\count_all(), create_test_model(), ActiveRecord\delete(), delete_test_models(), ActiveRecord\find_all(), ActiveRecord\find_by_id(), ActiveRecord\find_by_query(), ActiveRecord\has_and_belongs_to_many(), ActiveRecord\save(), and DBTest\test_get_connection().
Db::get_adapter ($name = DB_ADAPTER) static
Returns a database adapter registered under name.
Parameters
name A name associated to the adapter.
Definition at line 42 of file db.inc.php.
Referenced by DBTest\test_get_adapter(), and DBTest\test_register_adapter().
Db::get_connection ($name = DB_ADAPTER) static
Returns a connection for the requested adapter.
If a free connection is found in the pool it is returned to the caller, otherwise a new connection is created and added to the pool.
Parameters
name The name of the adapter
Definition at line 74 of file db.inc.php.
References DB_CONNECTION_KEY, DB_ID_KEY, and DB_IN_USE_KEY.
Referenced by ActiveRecord\__construct(), ActiveRecord\count_all(), create_test_model(), ActiveRecord\delete(), delete_test_models(), ActiveRecord\find_all(), ActiveRecord\find_by_id(), ActiveRecord\find_by_query(), ActiveRecord\has_and_belongs_to_many(), ActiveRecord\save(), and DBTest\test_get_connection().
Db::get_default_adapter () static
Returns the default database adapter.
Definition at line 62 of file db.inc.php.
Db::register_adapter ($adapter, $name) static
Registers a database adapter under name.
Parameters
adapter An instance of a class implementing the DbAdapter interface.
name A name associated to the adapter.
Definition at line 53 of file db.inc.php.
Referenced by DBTest\test_get_adapter(), DBTest\test_get_connection(), and DBTest\test_register_adapter().
static Db::show_pool () static
Definition at line 131 of file db.inc.php.
Member Data Documentation
Db::$adapters = array() static private
List of registered adapters.
Definition at line 25 of file db.inc.php.
Db::$conn_counter = 0 static private
Connections counter.
Definition at line 35 of file db.inc.php.
Db::$pool = array() static private
Connections pool.
Definition at line 30 of file db.inc.php.
The documentation for this class was generated from the following file:
include/db.inc.php