EmeRails: MysqlAdapter Class Reference
MysqlAdapter Class Reference
MySQL Database adapter.
Public Member Functions
connect ()
Connects to the database.
select_db ($database_name)
Selects the desired database.
close ()
Closes the connection to the database.
prepare ($query)
Prepares a query for execution.
exec ()
Executes a query.
insert_id ()
Returns the id generated by the last INSERT query.
escape ($value)
Escapes the given value to avoid SQL injections.
result ($pos=0, $colname=NULL)
Returns a single result of the last SELECT query.
num_rows ()
Returns the number of rows returned by a previous SELECT query.
affected_rows ()
Returns the number of rows affected by a previous INSERT, UPDATE or DELETE query.
fetch_assoc ()
Returns the current row of the resultset as an associative array.
fetch_array ()
Returns the current row of the resultset as an array.
free_result ()
Releases the result of the last query.
print_query ()
Prints the last query for debug.
Public Attributes
const NAME = "mysql"
Name of this adapter.
$link
Connection link to the database.
$query
Query for the database.
$result
The result of the last query.
Static Public Attributes
static $queries_count = 0
Counter for queries executed.
Detailed Description
MySQL Database adapter.
Definition at line 10 of file mysql_adapter.php.
Member Function Documentation
MysqlAdapter::affected_rows ()
Returns the number of rows affected by a previous INSERT, UPDATE or DELETE query.
Implements DbAdapter.
Definition at line 158 of file mysql_adapter.php.
MysqlAdapter::close ()
Closes the connection to the database.
Implements DbAdapter.
Definition at line 70 of file mysql_adapter.php.
MysqlAdapter::connect ()
Connects to the database.
Implements DbAdapter.
Definition at line 46 of file mysql_adapter.php.
Referenced by escape(), exec(), prepare(), and select_db().
MysqlAdapter::escape ($value)
Escapes the given value to avoid SQL injections.
Parameters
value The value to escape.
Implements DbAdapter.
Definition at line 127 of file mysql_adapter.php.
References connect().
MysqlAdapter::exec ()
Executes a query.
Implements DbAdapter.
Definition at line 103 of file mysql_adapter.php.
References $result, connect(), and result().
MysqlAdapter::fetch_array ()
Returns the current row of the resultset as an array.
Implements DbAdapter.
Definition at line 176 of file mysql_adapter.php.
References result().
MysqlAdapter::fetch_assoc ()
Returns the current row of the resultset as an associative array.
Implements DbAdapter.
Definition at line 167 of file mysql_adapter.php.
References result().
MysqlAdapter::free_result ()
Releases the result of the last query.
Implements DbAdapter.
Definition at line 185 of file mysql_adapter.php.
References result().
MysqlAdapter::insert_id ()
Returns the id generated by the last INSERT query.
Implements DbAdapter.
Definition at line 117 of file mysql_adapter.php.
MysqlAdapter::num_rows ()
Returns the number of rows returned by a previous SELECT query.
Implements DbAdapter.
Definition at line 149 of file mysql_adapter.php.
References result().
MysqlAdapter::prepare ($query)
Prepares a query for execution.
Parameters
query The query to execute.
Implements DbAdapter.
Definition at line 80 of file mysql_adapter.php.
References $query, connect(), and print_query().
MysqlAdapter::print_query ()
Prints the last query for debug.
Implements DbAdapter.
Definition at line 194 of file mysql_adapter.php.
Referenced by prepare().
MysqlAdapter::result ($pos = 0, $colname = NULL)
Returns a single result of the last SELECT query.
Parameters
row The row of the resultset.
colname The name (or the alias, if applicable) of the desired row.
Implements DbAdapter.
Definition at line 140 of file mysql_adapter.php.
Referenced by exec(), fetch_array(), fetch_assoc(), free_result(), and num_rows().
MysqlAdapter::select_db ($database_name)
Selects the desired database.
Parameters
database_name The name of the database.
Implements DbAdapter.
Definition at line 60 of file mysql_adapter.php.
References connect().
Member Data Documentation
MysqlAdapter::$link
Connection link to the database.
link
Definition at line 28 of file mysql_adapter.php.
MysqlAdapter::$queries_count = 0 static
Counter for queries executed.
queries_count
Definition at line 22 of file mysql_adapter.php.
MysqlAdapter::$query
Query for the database.
query
Definition at line 34 of file mysql_adapter.php.
Referenced by prepare().
MysqlAdapter::$result
The result of the last query.
result
Definition at line 40 of file mysql_adapter.php.
Referenced by exec().
const MysqlAdapter::NAME = "mysql"
Name of this adapter.
NAME
Definition at line 16 of file mysql_adapter.php.
The documentation for this class was generated from the following file:
include/mysql_adapter.php