EmeRails: HTTP Class Reference
HTTP Class Reference
HTTP helper object.
Static Public Member Functions
static void error (int $code=500, array $headers=array())
Detailed Description
HTTP helper object.
Project EmeRails - Codename Ocarina
© 2008 Claudio Procida http://www.emeraldion.it
Definition at line 13 of file http.php.
Member Function Documentation
static void HTTP::error (int $ code = 500, array $ headers = array()) [static]
Definition at line 21 of file http.php.
Referenced by BaseController::load_part_contents(), BaseController::render_page(), and BaseController::unknown_action().
The documentation for this class was generated from the following file:
/Users/delphine/Sviluppo/SVN/emeraldion.it/ocarina/helpers/http.php